In [1]:
import numpy as np

In [2]:
threeDarray = np.array([[[1,2,3]]])
print(threeDarray)

[[[1 2 3]]]


In [7]:
print(threeDarray.ndim)
print(threeDarray[0][0][1])

3
2


In [8]:
print(threeDarray[0,0,1])

2


In [9]:
print(threeDarray.shape)

(1, 1, 3)


In [11]:
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3


In [12]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
onesArray = np.ones(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
onesArray = onesArray.astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


In [16]:
preFilledArray = np.full(10,5)
print(preFilledArray)

[5 5 5 5 5 5 5 5 5 5]


In [25]:
matrix = np.array([[1,2,3,], [4,5,6]])
pyList = [[1,2,3],[1,2,3]]
print(matrix)

[[1 2 3]
 [4 5 6]]


In [26]:
print (matrix + 2) # with list it will throw error

[[3 4 5]
 [6 7 8]]


In [27]:
print (matrix - 2) # with list it will throw error

[[-1  0  1]
 [ 2  3  4]]


In [28]:
print (matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [29]:
print (pyList * 2)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [30]:
print (matrix / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [31]:
print (matrix // 2)

[[0 1 1]
 [2 2 3]]


In [33]:
print (pyList / 2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [34]:
print (matrix ** 2)

[[ 1  4  9]
 [16 25 36]]


In [35]:
print (matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
matrix1 = np.array([[1,2,3],[4,5,6],[0,0,0]])
matrix2 = np.array([[-1,-2,-3],[-4,-5,-6],[0,0,0]])

In [55]:
print(matrix1 + matrix2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [56]:
print(matrix1 - matrix2)

[[ 2  4  6]
 [ 8 10 12]
 [ 0  0  0]]


In [57]:
print(matrix1 * matrix2)

[[ -1  -4  -9]
 [-16 -25 -36]
 [  0   0   0]]


In [58]:
print(matrix1 / matrix2)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [nan nan nan]]


C:\Users\Adem_\AppData\Local\Temp\ipykernel_1444\2290127727.py:1: RuntimeWarning: invalid value encountered in divide
  print(matrix1 / matrix2)


In [59]:
print(matrix1 // matrix2)

[[-1 -1 -1]
 [-1 -1 -1]
 [ 0  0  0]]


C:\Users\Adem_\AppData\Local\Temp\ipykernel_1444\232832599.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(matrix1 // matrix2)


In [60]:
np.matmul(matrix1,matrix2) # Matrix multiplication

array([[ -9, -12, -15],
       [-24, -33, -42],
       [  0,   0,   0]])

In [61]:
np.min(matrix1)

0

In [62]:
np.max(matrix1)

6

In [63]:
np.sum(matrix1)

21

In [64]:
np.mean(matrix1)

2.3333333333333335

In [65]:
np.std(matrix1)

2.160246899469287

In [66]:
np.median(matrix1)

2.0